<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C200305150814.BAA26641%40hpcll183.cup.hp.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001716.html">
   <LINK REL="Next"  HREF="001718.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions</H1>
    <B>Dennis Handly</B> 
    <A HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C200305150814.BAA26641%40hpcll183.cup.hp.com%3E"
       TITLE="[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions">dhandly at cup.hp.com
       </A><BR>
    <I>Thu May 15 08:14:57 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="001716.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
        <LI>Next message: <A HREF="001718.html">PATCH: Define &quot;POD for the purpose of layout&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1717">[ date ]</a>
              <a href="thread.html#1717">[ thread ]</a>
              <a href="subject.html#1717">[ subject ]</a>
              <a href="author.html#1717">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>A function can exit either by use of &quot;return&quot; (including falling off the
</I>&gt;<i>If a destructor catches the exception, it does not exit by throwing an
</I>&gt;<i>exception.  So, yes, the situation you describe is legal.
</I>Mark Mitchell &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">mark at codesourcery.com</A>&gt;

Ok, so the only way to distinguish these exiting throws is to wrap the
call with:   try { ... } catch(...) { std::terminate(); }

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001716.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
	<LI>Next message: <A HREF="001718.html">PATCH: Define &quot;POD for the purpose of layout&quot;
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1717">[ date ]</a>
              <a href="thread.html#1717">[ thread ]</a>
              <a href="subject.html#1717">[ subject ]</a>
              <a href="author.html#1717">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">More information about the cxx-abi-dev
mailing list</a><br>
</body></html>
